### ISSUE TITLE
Fails to resolve dynamic require

### ISSUE THREAD

**Issue by Thom1729** [airtap/airtap#302]
tl;dr: Airtap fails to resolve `require(some_variable)`. I'm new to airtap and to tape, so I may be missing something obvious.

Minimal-ish example:

```
airtap-test/
  lib/
    mylib.js
  test/
    mytest.js
  package.json
  package-lock.json
```

mylib.js:
```js
module.exports.my_favorite_number = 1729;
```

mytest.js:
```js
const test = require('tape');
const mylib_path = '../lib/mylib';
const mylib = require(mylib_path);

test("Favorite number", function(t) {
    t.test(".my_favorite_number", function(t) {
        t.equal(mylib.my_favorite_number, 1729);
        t.end();
    })
});
```

Output of `npx tape test/mytest.js`:

```
TAP version 13
# Favorite number
# .my_favorite_number
ok 1 should be strictly equal

1..1
# tests 1
# pass  1

# ok
```

Output of `npx airtap test/mytest.js`:
```
client error (Default browser): {
  message: "Uncaught Error: Cannot find module '../lib/mylib'",
  source: 'http://localhost:50413/airtap/test.js',
  lineno: 1,
  colno: 199,
  error: {
    name: 'Error',
    stack: "Error: Cannot find module '../lib/mylib'\n" +
      '    at o (http://localhost:50413/airtap/test.js:1:159)\n' +
      '    at http://localhost:50413/airtap/test.js:1:316\n' +
      '    at Object./Users/thom/Repositories/airtap-test/test/mytest.js.tape (http://localhost:50413/airtap/test.js:10646:15)\n' +
      '    at o (http://localhost:50413/airtap/test.js:1:265)\n' +
      '    at r (http://localhost:50413/airtap/test.js:1:431)\n' +
      '    at http://localhost:50413/airtap/test.js:1:460'
  }
}
```

(At this point, I ctrl-C'd.)

When I replace `require(mylib_path)` with `require('../lib/mylib')`, airtap works fine:
```
TAP version 13
# Favorite number
# .my_favorite_number
ok 1 should be strictly equal

1..1
# tests 1
# pass  1

# ok

# 1 of 1 browsers ok
```

**Comment by vweevers** [comment]
This happens because `airtap` bundles the code into a single file using `browserify`, and dynamic requires can't be recognized ahead of time, so `browserify` does not know it should include `../lib/mylib` in the bundle.

Thanks for the excellent example!
