### ISSUE TITLE
Uncaught internal error when using more than one airtap-system browser

### ISSUE THREAD

**Issue by Krinkle** [airtap/airtap#336]
It seems whenever more than one system browser is in use (either listing two names in airtap.yml, or by using `--all`), the command consistently fails with an uncaught error. I'm using Node.js 21 from Homebrew, on macOS.

```tap
/qunit/test/integration/airtap/$ npx airtap -a pass-basic.js
TAP version 13
# System Google Chrome 126.0.6478.127 [1]
ok 1 exampleFoo [1]
ok 2 exampleBar [1]
ok 3 exampleBaz [1]
1..3
# pass 3 [1]
# skip 0 [1]
# todo 0 [1]
# fail 0 [1]
TAP version 13
# System Mozilla Firefox 127.0.2 [2]
ok 1 exampleFoo [2]
ok 2 exampleBar [2]
ok 3 exampleBaz [2]
1..3
# pass 3 [2]
# skip 0 [2]
# todo 0 [2]
# fail 0 [2]

/Users/krinkle/Development/qunit/test/integration/airtap/node_modules/airtap/bin/airtap.js:152
  throw err
  ^
143
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v21.1.0
```
```
$ NODE_OPTIONS='--trace-uncaught' npx airtap -a pass-basic.js
…

/Users/krinkle/Development/qunit/test/integration/airtap/node_modules/airtap/bin/airtap.js:152
  throw err
  ^
143
Thrown at:
    at fail (/Users/krinkle/Development/qunit/test/integration/airtap/node_modules/airtap/bin/airtap.js:152:3)
    at emit (node:events:515:28)
    at destroy (/Users/krinkle/Development/qunit/test/integration/airtap/node_modules/airtap/lib/test.js:30:12)
    at /Users/krinkle/Development/qunit/test/integration/airtap/node_modules/airtap/lib/airtap.js:107:18
    at onclose (/Users/krinkle/Development/qunit/test/integration/airtap/node_modules/nanoresource/index.js:131:37)
    at next (/Users/krinkle/Development/qunit/test/integration/airtap/node_modules/nanoresource-collection/index.js:112:36)
    at onclose (/Users/krinkle/Development/qunit/test/integration/airtap/node_modules/nanoresource/emitter.js:139:37)
    at /Users/krinkle/Development/qunit/test/integration/airtap/node_modules/airtap/lib/content-server.js:97:7
    at onceWrapper (node:events:629:28)
    at emit (node:events:515:28)
```

Isolated example at: https://github.com/Krinkle/qunit/blob/7fab4ffe80cd2ac05ad8c220793e177c9897cff9/test/integration/airtap/README.md

The input file is:

```js
require('./qunit/qunit.js');
QUnit.reporters.tap.init(QUnit);

QUnit.test('exampleFoo', function (assert) {
  assert.true(true, 'x');
});
QUnit.test('exampleBar', function (assert) {
  assert.true(true, 'y');
});
QUnit.test('exampleBaz', function (assert) {
  assert.true(true, 'z');
});
```
```yaml
timeout: 5s
retries: 0

providers:
  - airtap-system

browsers:
  - name: ff
```

It passes with `npx airtap pass-basic.js`. It fails when using `npx airtap -a pass-basic.js` and/or when adding `- name: chrome` to the configuration file.

**Comment by Krinkle** [comment]
Looks like it's actually specific to Chrome. It also fails with a single browser when using:

```yaml
browsers:
  - name: chrome
```

```
$ NODE_OPTIONS='--trace-uncaught' npx airtap --verbose pass-basic.js
  airtap-multi 2 manifests +0ms
  airtap:browserify file '/Users/krinkle/Development/qunit/test/integration/airtap/pass-basic.js' +0ms
  airtap:content-server active on port 64990 +0ms
  airtap:message-server active on port 64991 +0ms
  airtap:proxy-server active on localhost:64992 +0ms
  airtap:browser-context opening 'System Google Chrome 126.0.6478.127' +0ms
  airtap-system:launcher manifest: {
  airtap-system:launcher   name: 'chrome',
  airtap-system:launcher   command: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  airtap-system:launcher   version: '126.0.6478.127',
  airtap-system:launcher   channel: 'stable',
  airtap-system:launcher   supports: { headless: true },
  airtap-system:launcher   options: { headless: true },
  airtap-system:launcher   title: 'System Google Chrome 126.0.6478.127',
  airtap-system:launcher   wants: {},
  airtap-system:launcher   provider: 'airtap-system'
  airtap-system:launcher } +0ms
  airtap-system:launcher spawn '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' [ '--user-data-dir=/private/var/folders/_5/khc4z6kx4nbg4mn5wxyzbsn40000gn/T/3cb441840267b9cebcda46d0456a9489', '--headless', '--remote-debugging-port=9222', '--disable-restore-session-state', '--no-default-browser-check', '--disable-popup-blocking', '--disable-translate', '--start-maximized', '--disable-default-apps', '--disable-sync', '--enable-fixed-layout', '--no-first-run', '--noerrdialogs', 'http://localhost:64992/airtap' ] +0ms
  airtap:browser-session session 'System Google Chrome 126.0.6478.127' +0ms
  airtap:browser-context ready 'System Google Chrome 126.0.6478.127' +236ms
TAP version 13
ok 1 exampleFoo
ok 2 exampleBar
ok 3 exampleBaz
1..3
# pass 3
# skip 0
# todo 0
# fail 0
  airtap:browser-session session 'System Google Chrome 126.0.6478.127' complete (ok) +112ms
  airtap:browser-session ending 'System Google Chrome 126.0.6478.127' +1ms
  airtap:browser-context closing 'System Google Chrome 126.0.6478.127' +114ms
  airtap closing +0ms

/Users/krinkle/Development/qunit/test/integration/airtap/node_modules/airtap/bin/airtap.js:152
  throw err
  ^
143
Thrown at:
    at fail (/Users/krinkle/Development/qunit/test/integration/airtap/node_modules/airtap/bin/airtap.js:152:3)
    at emit (node:events:515:28)
    at destroy (/Users/krinkle/Development/qunit/test/integration/airtap/node_modules/airtap/lib/test.js:30:12)
    at /Users/krinkle/Development/qunit/test/integration/airtap/node_modules/airtap/lib/airtap.js:107:18
    at onclose (/Users/krinkle/Development/qunit/test/integration/airtap/node_modules/nanoresource/index.js:131:37)
    at next (/Users/krinkle/Development/qunit/test/integration/airtap/node_modules/nanoresource-collection/index.js:112:36)
    at onclose (/Users/krinkle/Development/qunit/test/integration/airtap/node_modules/nanoresource/emitter.js:139:37)
    at /Users/krinkle/Development/qunit/test/integration/airtap/node_modules/airtap/lib/content-server.js:97:7
    at onceWrapper (node:events:629:28)
    at emit (node:events:515:28)


Node.js v21.1.0
```
