### ISSUE TITLE
`airtap -la` error in demo project

### ISSUE THREAD

**Issue by nichoth** [airtap/airtap#338]
1. Install airtap
```sh
npm i -D airtap
```

2. run [command in demo repo](https://github.com/airtap/demo?tab=readme-ov-file#usage):

```sh
npx airtap -la
```

3. Error: "Cannot find module 'airtap-system'"

```
$ npx airtap -la

node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module 'airtap-system'
Require stack:
- /Users/nick/code/earthworm/node_modules/airtap-multi/index.js
- /Users/nick/code/earthworm/node_modules/airtap/lib/airtap.js
- /Users/nick/code/earthworm/node_modules/airtap/bin/airtap.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at MultiProvider.add (/Users/nick/code/earthworm/node_modules/airtap-multi/index.js:24:24)
    at MultiProvider.add (/Users/nick/code/earthworm/node_modules/airtap-multi/index.js:40:14)
    at Airtap.provider (/Users/nick/code/earthworm/node_modules/airtap/lib/airtap.js:27:18)
    at Object.<anonymous> (/Users/nick/code/earthworm/node_modules/airtap/bin/airtap.js:111:8)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/nick/code/earthworm/node_modules/airtap-multi/index.js',
    '/Users/nick/code/earthworm/node_modules/airtap/lib/airtap.js',
    '/Users/nick/code/earthworm/node_modules/airtap/bin/airtap.js'
  ]
}

Node.js v20.16.0
```

**Comment by vweevers** [comment]
I suspect you left out a step, because `airtap` and the demo repository don't import `airtap-system` by default. Did you perhaps modify [`.airtap.yml`](https://github.com/airtap/demo/blob/master/.airtap.yml)? If you added `airtap-system` there, you will also need to install it with `npm i airtap-system` before it can be used.

In addition, the output of your third step suggests that you're not running `airtap -la` in the demo repository; the working directory seems to be `/Users/nick/code/earthworm`. Which makes the demo repository irrelevant.

**Comment by nichoth** [comment]
Thanks for quick response. I can confirm issue was config, demo project is working as expected.

**Comment by nichoth** [comment]
To add some details, I did not realize that `.airtap.yml` could define dependencies, and I did not get that from my cursory look at the docs/guide. I expected all dependencies to be defined in `airtap`'s `package.json`.

**Comment by vweevers** [comment]
Thanks for the feedback! I tweaked the README in https://github.com/airtap/airtap/commit/5cc227e363337ab989319ac20dc7646b8c89aeec.
