### ISSUE TITLE
airtap --list-available-browsers broken

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#82]
```
$ airtap --list-available-browsers
Error:
Airtap tried to run tests in saucelabs, however no saucelabs credentials were provided.
See the zuul wiki (https://github.com/defunctzombie/zuul/wiki/Cloud-testing) for info on how to setup cloud testing.
```

Problem is not returning in `bin/airtap.js` (due to erroneous `standard` fix).

I had a quick look at it and adding an `else` case _should_ do the trick but there are more problems:

```
$ airtap --list-available-browsers
microsoftedge
/home/lms/src/airtap/airtap/bin/airtap.js:96
      var versions = _.uniq(_.pluck(allBrowsers[browser], 'version')).sort(function (a, b) {
                              ^

TypeError: _.pluck is not a function
    at /home/lms/src/airtap/airtap/bin/airtap.js:96:31
    at IncomingMessage.<anonymous> (/home/lms/src/airtap/airtap/lib/scout_browser.js:35:7)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

I suspect this was due to updating `lodash` which we never caught with tests. When fixing this, lets write a test for this.

**Comment by vweevers** [comment]
While we're at it, how about shortening it to `--list-browsers`? Or adding an alias `-l`.

**Comment by ralphtheninja** [comment]
When fixing this, also fix standard for `bin/airtap.js`

**Comment by ralphtheninja** [comment]
I think we should release `0.0.3` once this is fixed. Always nice to get bugs out of the way as quick as possible.
